# Generated by Django 3.0.2 on 2021-03-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.CharField(blank=True, default='This is a default', help_text='A field for testing', max_length=255, verbose_name='Test Field')),
            ],
        ),
    ]
